### ISSUE TITLE
As a user I need to be able to review networking information.

### ISSUE THREAD

**Issue by zitnik** [ManageIQ/manageiq-providers-cisco_intersight#10]
This is part of the inventory which we are going to be collecting in this first batch. The idea is that we collect the following information:
    • All relevant data about the physical server.
    • All relevant data about the racks and chasis
    • All relevant data about the storage accompanied with the server
    • All relevant data about the networking interfaces. This does currently not include networking equipment as we need to understand first how does this come together in Intersight.
For Tucson lab when opening a server inventory, we get the following message about the license.
![us1](https://user-images.githubusercontent.com/7016255/146573999-818c0a6a-5123-42d9-bfe7-f54cda6b385a.png)

Situation in CaaS lab is a bit different where we get the following
![us2](https://user-images.githubusercontent.com/7016255/146574087-2ce5b6a8-add1-4483-ba24-e8cb4e7e6b5a.png)

**Comment by tjazsch** [comment]
Resolved by #35 and #39.
