### ISSUE TITLE
As a user I need to be able to view server logs in ManageIQ

### ISSUE THREAD

**Issue by zitnik** [ManageIQ/manageiq-providers-cisco_intersight#14]

**Comment by alescernivec** [comment]
At this point we believe that this is not possible with the provider since Intersight API does not provide any endpoint/resource we could use for getting the server logs to the providers' side. I would also need to check how this is done in other providers' (if it even is done so).

**Comment by agrare** [comment]
Hey @alescernivec host logs are typically collected via Host SmartState Analysis: https://github.com/ManageIQ/manageiq/blob/master/app/models/host.rb#L1360

If it is possible to ssh to the host you could pull the logs that way.

**Comment by alescernivec** [comment]
Great, thanks for the pointer. Unfortunately, we do not have ssh access to the hosts. In our case the logs should be accessible via API from the Intersight (or somehow via vKVM), but there are limitations to that. We will need to do more research around this.
