### ISSUE TITLE
I get error: Failure/Error: require 'bootsnap/setup'

### ISSUE THREAD

**Issue by tjazsch** [ManageIQ/manageiq-providers-cisco_intersight#36]
Hey!

While trying to run tests by running `bundle exec rake app:spec:models` from the folder plugins/manageiq-providers-cisco_intersight for the new inventory features (mostly developed by this PR: https://github.com/ManageIQ/manageiq-providers-cisco_intersight/pull/35). I get the following error:

![image](https://user-images.githubusercontent.com/92620429/159123262-bcb0cc24-ae44-4615-a5a4-25d8553190d4.png)

I've had similar problem with bootsnap before for entering rails server and console. @Fryguy helped me solve it in this issue: https://github.com/ManageIQ/manageiq-providers-cisco_intersight/issues/34 (the solution was to remove bootsnap cache directory in core. So that is, running `rm -rf ../../tmp/cache/bootsnap` from the provider).

This time, even after removing bootsnap running tests doesn't work. 

Any ideas how to resolve this error and successfully run tests?

Thanks!

**Comment by tjazsch** [comment]
Steps to reproduce: Use the WIP pull request that targets networking and inventory in general (https://github.com/ManageIQ/manageiq-providers-cisco_intersight/pull/35). This PR contains tests that may be ran by calling `bundle exec rake app:spec:models` from the provider. 

Also, before developing the networking functionality, the tests worked out fine and I haven't been able to locate the place where this error could possibly occur.

**Comment by Fryguy** [comment]
Is this the same error you hit in #34 ?  Did you try removing the cache like there?  I'm curious why this keeps happening on your machine but doesn't happen on any of ours.

**Comment by tjazsch** [comment]
Hey,

sorry for the delay and thanks for the responses. I managed to fix the bootstrap error I've been getting by deleting `.bundle/ruby/2.6.0/gems` directory from the core (the place where the gems, installed through bundle were for me) and  at the same time removing the bootstrap gem (I don't remember by heart where the bootstrap gem was installed) and just reinstalling them again by using `bundle install`. Thanks again for the help. :D
