### ISSUE TITLE
View of a list of Server Profiles available in the system indicating which all are associated with servers

### ISSUE THREAD

**Issue by alescernivec** [ManageIQ/manageiq-providers-cisco_intersight#37]
As a user I should be able to view a list of server profiles available in the system indicating which all are associated with servers and which are not so that I get a full view of the inventory. 

More details on Server Profiles reside [here](https://www.cisco.com/c/en/us/td/docs/unified_computing/Intersight/b_Intersight_Managed_Mode_Configuration_Guide/b_intersight_managed_mode_guide_chapter_0100.html#reference_wsb_nsv_r2b ). 

For this purpose we should extend miq collections with additional one, e.g. `physical_server_profiles` with a reference on the `physical_server`. 

Moreover, we should have a list of the available server profiles listed in the physical provider's view (within the ManageIQ).

What is the best approach for this?

**Comment by alescernivec** [comment]
@agrare - we had a discussion regarding this in the last call. I believe that you mentioned VMWare's provider's collections. Could you please point us to these? Are there any collections we could reuse here?

**Comment by agrare** [comment]
Thanks @alescernivec I'm reviewing the docs that you posted and will update in a bit

**Comment by agrare** [comment]
Hey @alescernivec sorry for the delay.  So a server profile isn't just a "oneshot" configuration during provisioning, but rather stays with the server over its lifetime? (per "Server Profile Drift" section)  In that case it doesn't sound like a `ConfigurationSpec` which is only using once during initial provisioning.

Creating a new table / model for a `PhysicalServerProfile` sounds like the way to go here, this would also allow us to perform the redeploy operation if a server changes away from the profile.

**Comment by alescernivec** [comment]
Resolved in #42
